// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIStatus() {
  return window['go']['main']['App']['APIStatus']();
}

export function DataDirectory() {
  return window['go']['main']['App']['DataDirectory']();
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function HasNativePrinting() {
  return window['go']['main']['App']['HasNativePrinting']();
}

export function ListPrinters() {
  return window['go']['main']['App']['ListPrinters']();
}

export function PrintPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['PrintPDF'](arg1, arg2, arg3);
}
