// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function APIStatus():Promise<string>;

export function DataDirectory():Promise<string>;

export function FrontendReady():Promise<boolean>;

export function HasNativePrinting():Promise<boolean>;

export function ListPrinters():Promise<Array<main.PrinterInfo>>;

export function PrintPDF(arg1:string,arg2:string,arg3:string):Promise<void>;
